import "./globals.css";
import type { Metadata } from "next";
import { Volkhov, Poppins } from "next/font/google";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const volkhov = Volkhov({
  subsets: ["latin"],
  weight: "400",
  variable: "--font--volkhov",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font--poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${volkhov.variable}  ${poppins.variable} `}>
        <section className="m-12">
          <Providers>{children}</Providers>
        </section>
      </body>
    </html>
  );
  ``;
}
